# Generated by Django 5.1.4 on 2024-12-23 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('otp_enabled', models.BooleanField(default=False)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('auth_date', models.DateTimeField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
